services:
  caddy:
    image: registry.gitlab.com/informatiger/caddy-inwx:2.8.4-alpine
    restart: unless-stopped
    environment: 
      INWX_USER: ${INWX_USER}
      INWX_PASSWD: ${INWX_PASSWD}
    networks:
      - caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./conf:/etc/caddy"
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy:
    name: caddy
    external: true
